### ISSUE TITLE
Magic dagger (and anything else that's resprited probably if anything)

### ISSUE THREAD

**Issue by JonaBlackstar** [Exxo-Avalon/AvalonTesting#25]
When I turn off the mod and then put a magic dagger in my inventory or have it appear in the list of items with the hero's mod item browser it just breaks the inventory/item viewer thingy. Magic dagger is also invisible 👍

**Comment by blahblahbal** [comment]
Possibly works now?

**Comment by blahblahbal** [comment]
Fixed
